In [12]:
import requests
from bs4 import BeautifulSoup
url="https://altibbi.com/%D8%A7%D8%B3%D8%A6%D9%84%D8%A9-%D8%B7%D8%A8%D9%8A%D8%A9/%D8%A7%D9%85%D8%B1%D8%A7%D8%B6-%D8%A7%D9%84%D8%AC%D9%87%D8%A7%D8%B2-%D8%A7%D9%84%D8%AA%D9%86%D9%81%D8%B3%D9%8A"
response=requests.get(url)
soup=BeautifulSoup(response.text,"html.parser")
print(soup.prettify())

<!DOCTYPE html>
<html lang="ar-US">
 <head>
  <title>
   أسئلة وأجوبة طبية - أمراض الجهاز التنفسي | الطبي
  </title>
  <script type="application/ld+json">
   {
    "@context": "https://schema.org",
    "@type": "WebPage",
    "@id": "https://altibbi.com/اسئلة-طبية/%D8%A7%D9%85%D8%B1%D8%A7%D8%B6-%D8%A7%D9%84%D8%AC%D9%87%D8%A7%D8%B2-%D8%A7%D9%84%D8%AA%D9%86%D9%81%D8%B3%D9%8A#webpage",
    "url": "https://altibbi.com/اسئلة-طبية/%D8%A7%D9%85%D8%B1%D8%A7%D8%B6-%D8%A7%D9%84%D8%AC%D9%87%D8%A7%D8%B2-%D8%A7%D9%84%D8%AA%D9%86%D9%81%D8%B3%D9%8A",
    "name": "أسئلة وأجوبة طبية - أمراض الجهاز التنفسي",
    "description": "أسئلة الأعضاء عن أمراض الجهاز التنفسي  وإجابات الأطباء المختصين عليها. أرسل سؤالك الآن عن أي موضوع طبي أو صحي على الطبي",
    "inLanguage": "ar-US"
}
  </script>
  <script>
   const IS_MOBILE = /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent);
  </script>
  <meta charset="utf-8"/>
  <meta content="width=device-width, initial-scale=1.0, maximum-scale=5.0" name="viewport"/>
  <meta content="Altibbi.com" name="author"/>
  <!-- Chrome, Firefox OS and Opera -->
  <meta content="#102A56" name="theme-color"/>
  <!-- Windows Phone -->
  <meta content="#195895" name="msapplication-navbutton-color"/>
  <!-- iOS Safari -->
  <meta content="#102A56" name="apple-mobile-web-app-status-bar-style"/>
  <meta content="yes" name="apple-mobile-web-app-capable">
   <meta content="yes" name="mobile-web-app-capable"/>
   <meta content="146667996661" property="fb:pages">
    <meta content="أسئلة الأعضاء عن أمراض الجهاز التنفسي  وإجابات الأطباء المختصين عليها. أرسل سؤالك الآن عن أي موضوع طبي أو صحي على الطبي" name="description"/>
    <meta content="IE=edge" http-equiv="X-UA-Compatible"/>
    <meta content="253132216348515" property="fb:app_id">
     <meta content="أسئلة وأجوبة طبية - أمراض الجهاز التنفسي | الطبي" property="og:title">
      <meta content="https://altibbi.com/اسئلة-طبية/%D8%A7%D9%85%D8%B1%D8%A7%D8%B6-%D8%A7%D9%84%D8%AC%D9%87%D8%A7%D8%B2-%D8%A7%D9%84%D8%AA%D9%86%D9%81%D8%B3%D9%8A" property="og:url">
       <meta content="https://cdn.altibbi.com/global/altibbi-imgs/altibbi_logo_1200_630.png" property="og:image:secure_url">
        <meta content="https://cdn.altibbi.com/global/altibbi-imgs/altibbi_logo_1200_630.png" property="og:image">
         <meta content="1200" property="og:image:width">
          <meta content="630" property="og:image:height">
           <meta content="الطبي" property="og:site_name"/>
           <meta content="أسئلة الأعضاء عن أمراض الجهاز التنفسي  وإجابات الأطباء المختصين عليها. أرسل سؤالك الآن عن أي موضوع طبي أو صحي على الطبي" property="og:description"/>
           <meta content="website" property="og:type"/>
           <meta content="موقع الطبي للمعلومات الصحية والاستشارات الطبية | أمراض، أدوية وعلاج" property="og:image:alt"/>
           <meta content="summary" property="twitter:card"/>
           <meta content="@Altibbi" property="twitter:site"/>
           <meta content="@Altibbi" property="twitter:creator"/>
           <meta content="أسئلة وأجوبة طبية - أمراض الجهاز التنفسي | الطبي" property="twitter:title"/>
           <meta content="أسئلة الأعضاء عن أمراض الجهاز التنفسي  وإجابات الأطباء المختصين عليها. أرسل سؤالك الآن عن أي موضوع طبي أو صحي على الطبي" property="twitter:description"/>
           <meta content="https://cdn.altibbi.com/global/altibbi-imgs/altibbi_logo_1200_630.png" property="twitter:image"/>
           <meta content="أسئلة وأجوبة طبية - أمراض الجهاز التنفسي" property="twitter:image:alt"/>
           <meta content="_csrf-frontend" name="csrf-param"/>
           <meta content="vwPOtpi-dyVmP7eepFDgt1MNdZg7k6i3ubeupCYizGLnNqmPzswnTgRPwPfyE4juP3U__nX8ndDfzvbibQ_7IA==" name="csrf-token"/>
           <link href="https://altibbi.com/اسئلة-طبية/%D8%A7%D9%85%D8%B1%D8%A7%D8%B6-%D8%A7%D9%84%D8%AC%D9%87%D8%A7%D8%B2-%D8%A7%D9%84%D8%AA%D9%86%D9%81%D8%B3%D9%8A" rel="canonical"/>
           <link href="/اسئلة-طبية/%D8%A7%D9%85%D8%B1%D8%A7%D8%B6-%D8%A7%D9%84%D8%AC%D9%87%D8%A7%D8%B2-%D8%A7%D9%84%D8%AA%D9%86%D9%81%D8%B3%D9%8A" rel="self"/>
           <link href="/اسئلة-طبية/%D8%A7%D9%85%D8%B1%D8%A7%D8%B6-%D8%A7%D9%84%D8%AC%D9%87%D8%A7%D8%B2-%D8%A7%D9%84%D8%AA%D9%86%D9%81%D8%B3%D9%8A" rel="first"/>
           <link href="/اسئلة-طبية/%D8%A7%D9%85%D8%B1%D8%A7%D8%B6-%D8%A7%D9%84%D8%AC%D9%87%D8%A7%D8%B2-%D8%A7%D9%84%D8%AA%D9%86%D9%81%D8%B3%D9%8A?page=885" rel="last"/>
           <link href="/اسئلة-طبية/%D8%A7%D9%85%D8%B1%D8%A7%D8%B6-%D8%A7%D9%84%D8%AC%D9%87%D8%A7%D8%B2-%D8%A7%D9%84%D8%AA%D9%86%D9%81%D8%B3%D9%8A?page=2" rel="next"/>
           <link href="/assets/ed701eeb510c143208a70a74665d747c.css?v=1783931264" rel="stylesheet"/>
           <style>
            .dr_image {
width: 100%;
height: auto;
border-radius: 10px 10px 0 0;
}
.details_wrapper {
background: #1249CC;
padding: 20px;
text-align: center;
border-radius: 0 0 10px 10px;
}
.text_1, .text_2, .text_3 {
color: white;
}
.text_2 {
font-family: Tajawal;
font-size:24px;
}
.text_3 {
font-family: Tajawal;
}
.call_dr_btn {
background: white !important;
font-size: 18px;
width: 100%;
margin-top: 30px;
line-height: 35px;
height: 50px;
font-family: Tajawal;
}
@media(max-width: 768px) {
.details_wrapper {
margin-top: -1px;
}
.text-2 {
font-size: 27px;
}
}
           </style>
           <style>
            #contentNavigatorModal .modal-content{
    background-color: transparent;
    border: unset;
}

#contentNavigatorModal .modal-body{
    padding: 0 !important;
}

@media (min-width: 576px) {
    #contentNavigatorModal .modal-dialog{
        max-width: 360px;
    }
}

.content-navigator-modal-wrapper {
    border-radius: 12px;
    overflow: hidden;
    background-color: #ffffff;
}

.content-navigator-modal-wrapper .content-navigator-modal-image-wrapper {
    width: 100%;
    min-height: 292px;
    background-color: #155EEF;
    background-image: url('/theme/altibbi/images/content-navigator/modal_iphone.webp?v=1');
    background-repeat: no-repeat;
    background-position: center bottom;
    background-size: 100% auto;
    position: relative;
}

.content-navigator-modal-wrapper .content-navigator-modal-image-wrapper button{
    position: absolute;
    top: 12px;
    left: 12px;
    padding: 8px;
    opacity: .20;
}

.content-navigator-modal-wrapper .content-navigator-modal-content-wrapper {
    padding: 20px 16px 16px;
}

.content-navigator-modal-wrapper .content-navigator-modal-sub-title{
    color: #101828;
    text-align: center;
    font-family: Tajawal, sans-serif;
    font-size: 18px;
    line-height: 22px;
    font-weight: 700;
    margin-bottom: 6px;
}

.content-navigator-modal-wrapper .content-navigator-modal-main-title{
    color: #101828;
    text-align: center;
    font-family: Tajawal, sans-serif;
    font-size: 26px;
    line-height: 31px;
    font-weight: 700;
    margin-bottom: 6px;
}

.content-navigator-modal-wrapper .content-navigator-modal-note{
    color: #344054;
    text-align: center;
    font-family: Tajawal, sans-serif;
    font-size: 14px;
    line-height: 20px;
    font-weight: 700;
    margin-bottom: 24px;
}

.content-navigator-modal-wrapper a{
    color: #ffffff;
    text-align: center;
    font-family: Tajawal, sans-serif;
    font-size: 14px;
    line-height: 20px;
    font-weight: 700;
    background-color: #155EEF;
    border-radius: 8px;
    padding: 12px 18px;

    display: flex;
    justify-content: center;
    align-items: center;
    width: 100%;
    gap: 6px;
}

.content-navigator-modal-wrapper a:hover{
    background-color: #00bcaa;
}
           </style>
           <style>
            #contentNavigatorDownloadModal .modal-dialog-custom {
        max-width: 345px;
        width: 100%;
        display: flex;
        align-items: center;
        justify-content: center;
        min-height: calc(100vh - 1rem);
    }

    #contentNavigatorDownloadModal .btn-close-custom {
        top: 7px;
        left: 5px;
        z-index: 1051;
        font-size: 30px;
        color: #98A2B3;
        border: none;
        display: flex;
        align-items: center;
        justify-content: center;
    }

    #contentNavigatorDownloadModal .modal-image {
        width: 345px;
        height: 431px;
        cursor: pointer;
        border-radius: 12px;
        display: block;
        max-width: 100%;
    }

    @media (max-width: 768px) {
        #contentNavigatorDownloadModal .modal-dialog-custom {
            margin: unset;
            max-width: 100%;
        }

        #contentNavigatorDownloadModal .btn-close-custom {
            top: 12px;
            left: 12px;
            width: 28px;
            height: 28px;
            font-size: 16px;
        }
    }
           </style>
           <script>
            var s2options_e9bc2761 = {"themeCss":".select2-container--krajee-bs4","sizeCss":"","doReset":true,"doToggle":false,"doOrder":false};
window.select2_69d74bc2 = {"allowClear":true,"theme":"krajee-bs4","width":"auto","placeholder":"التصنيفات","language":"ar"};

var CHAT_WIDGET_MESSAGE_ONE = "مرحبا بك في الطبي";
var CHAT_WIDGET_MESSAGE_TWO = "هل لديك استفسار عن";
var CHAT_WIDGET_MESSAGE_THREE = "المواضيع الطبية؟";
var LATER = "ذكرني لاحقاً";
var CALL_DR = "تحدث مع طبيب ";
var MEDICAL_QUESTION = "لديك استفسار طبي؟";
var CONTACT_US_NOW = "contact_us_now";
var OUR_DRS_HERE = "our_drs_here";
var HOW_CAN_I_HELP = "أطباؤنا هنا لمساعدتك";
           </script>
           <link as="font" crossorigin="" href="/theme/altibbi/lib/fonts/Tajawal-Medium.woff2" rel="preload" type="font/ttf"/>
           <link as="font" crossorigin="" href="/theme/altibbi/lib/fonts/Tajawal-Regular.woff2" rel="preload" type="font/ttf"/>
           <link as="font" crossorigin="" href="/theme/altibbi/lib/fonts/Tajawal-Bold.woff2" rel="preload" type="font/ttf"/>
           <link href="/favicon.ico" rel="icon" sizes="any"/>
           <link href="/favicon.svg" rel="icon" type="image/svg+xml"/>
           <link href="/favicon-48x48.png" rel="icon" sizes="48x48" type="image/png"/>
           <link href="/favicon-32x32.png" rel="icon" sizes="32x32" type="image/png"/>
           <link href="/favicon-16x16.png" rel="icon" sizes="16x16" type="image/png"/>
           <link href="/apple-touch-icon.png" rel="apple-touch-icon" sizes="180x180"/>
           <link href="/manifest.json" rel="manifest"/>
           <link href="//cdn.altibbi.com" rel="dns-prefetch"/>
          </meta>
         </meta>
        </meta>
       </meta>
      </meta>
     </meta>
    </meta>
   </meta>
  </meta>
 </head>
 <body data-country="US">
  <script>
   let CURRENT_COUNTRY_ISO_CODE = "US";
    let COUNTRY_ID = "51";
    let MEMBER_ID = null;
    let MEMBER_SUBSCRIBED = 0;
    let ENABLE_RASA_CHAT = 0;
    let ENABLE_ALTIBBI_CHAT = 1;
    let ENABLE_ALTIBBI_GSM = 1;
    let DYNAMIC_CTAS_LINKS = {"widget_script":"\r\n(function () {\r\n  \"use strict\";\r\n\r\n  var EVENT_NAME = \"main_wa_click\";\r\n  var CLEVERTAP_EVENT_NAME = \"whatsapp_widget_clicked\";\r\n  var GCLID_KEY = \"ab_gclid\";\r\n  var UTM_SOURCE_KEY = \"ab_utm_source\";\r\n  var UTM_CAMPAIGN_KEY = \"ab_utm_campaign\";\r\n  var ATTRIBUTION_TTL_DAYS = 90;\r\n\r\n  function onReady(fn) {\r\n    if (document.readyState === \"loading\") {\r\n      document.addEventListener(\"DOMContentLoaded\", fn);\r\n    } else {\r\n      fn();\r\n    }\r\n  }\r\n\r\n  function isMobileUA() {\r\n    return /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(\r\n      navigator.userAgent\r\n    );\r\n  }\r\n\r\n  function safeLocalGet(key) {\r\n    try {\r\n      return localStorage.getItem(key);\r\n    } catch (e) {\r\n      return null;\r\n    }\r\n  }\r\n\r\n  function safeLocalSet(key, value) {\r\n    try {\r\n      localStorage.setItem(key, value);\r\n    } catch (e) {}\r\n  }\r\n\r\n  function safeLocalRemove(key) {\r\n    try {\r\n      localStorage.removeItem(key);\r\n    } catch (e) {}\r\n  }\r\n\r\n  function setWithTTL(key, value, ttlDays) {\r\n    safeLocalSet(\r\n      key,\r\n      JSON.stringify({\r\n        v: value,\r\n        e: Date.now() + ttlDays * 864e5\r\n      })\r\n    );\r\n  }\r\n\r\n  function getWithTTL(key) {\r\n    var raw = safeLocalGet(key);\r\n\r\n    if (!raw) return null;\r\n\r\n    try {\r\n      var rec = JSON.parse(raw);\r\n\r\n      if (!rec || typeof rec.e !== \"number\" || Date.now() > rec.e) {\r\n        safeLocalRemove(key);\r\n        return null;\r\n      }\r\n\r\n      return rec.v;\r\n    } catch (e) {\r\n      safeLocalRemove(key);\r\n      return null;\r\n    }\r\n  }\r\n\r\n  function pushEvent(payload) {\r\n    window.dataLayer = window.dataLayer || [];\r\n    window.dataLayer.push(payload);\r\n  }\r\n\r\n  function pushCleverTap(eventName, props) {\r\n    try {\r\n      if (\r\n        window.clevertap &&\r\n        clevertap.event &&\r\n        typeof clevertap.event.push === \"function\"\r\n      ) {\r\n        clevertap.event.push(eventName, props || {});\r\n      }\r\n    } catch (e) {}\r\n  }\r\n\r\n  onReady(function init() {\r\n    // Unique guard so this does not get blocked by another Altibbi widget\r\n    if (document.querySelector(\".ab-custom-wa-button\")) return;\r\n\r\n    var IS_MOBILE = isMobileUA();\r\n\r\n    var params = new URLSearchParams(window.location.search);\r\n\r\n    var gclidFromUrl = params.get(\"gclid\");\r\n    var utmSourceFromUrl = params.get(\"utm_source\");\r\n    var utmCampaignFromUrl = params.get(\"utm_campaign\");\r\n\r\n    if (gclidFromUrl) setWithTTL(GCLID_KEY, gclidFromUrl, ATTRIBUTION_TTL_DAYS);\r\n    if (utmSourceFromUrl) setWithTTL(UTM_SOURCE_KEY, utmSourceFromUrl, ATTRIBUTION_TTL_DAYS);\r\n    if (utmCampaignFromUrl) setWithTTL(UTM_CAMPAIGN_KEY, utmCampaignFromUrl, ATTRIBUTION_TTL_DAYS);\r\n\r\n    var gclid = gclidFromUrl || getWithTTL(GCLID_KEY) || null;\r\n    var utm_source = utmSourceFromUrl || getWithTTL(UTM_SOURCE_KEY) || null;\r\n    var utm_campaign = utmCampaignFromUrl || getWithTTL(UTM_CAMPAIGN_KEY) || null;\r\n\r\n    // Same single link on mobile and desktop, per your button spec.\r\n    var link = \"https://go.altibbi.com/global\";\r\n    var chatChannel = \"global\"; // destination label; drop it if you don't need it (device_type already covers device)\r\n    var pageType = document.body.getAttribute(\"data-page-type\") || window.location.pathname;\r\n\r\n    var style = document.createElement(\"style\");\r\n\r\n    style.textContent = `\r\n      .ab-custom-wa-button {\r\n        position: fixed;\r\n        bottom: 24px;\r\n        right: 25px;\r\n        z-index: 100;\r\n      }\r\n\r\n      .ab-custom-wa-button .whats-cta {\r\n        width: 250px !important;\r\n        height: 55px;\r\n        background-color: #25d366;\r\n        border-radius: 28px;\r\n        min-width: 50px;\r\n        box-shadow: 0 6px 18px rgb(0 0 0 / .20);\r\n        display: flex;\r\n        align-items: center;\r\n        justify-content: center;\r\n        color: #fff !important;\r\n        text-decoration: none;\r\n        transition: background-color .2s ease;\r\n        border: none;\r\n        font-size: 18px;\r\n        font-weight: 700;\r\n        line-height: 1;\r\n        -webkit-font-smoothing: antialiased;\r\n      }\r\n\r\n      .ab-custom-wa-button .whats-cta:hover {\r\n        background-color: #20b959;\r\n        color: #fff !important;\r\n      }\r\n\r\n      .ab-custom-wa-button .whats-cta:focus-visible {\r\n        outline: 2px solid #fff;\r\n        outline-offset: 2px;\r\n      }\r\n\r\n      @media (max-width: 767px) {\r\n        .ab-custom-wa-button {\r\n          right: 15px;\r\n          bottom: 24px;\r\n        }\r\n\r\n        .ab-custom-wa-button .whats-cta {\r\n          width: 230px !important;\r\n          height: 54px;\r\n          font-size: 17px;\r\n        }\r\n      }\r\n    `;\r\n\r\n    document.head.appendChild(style);\r\n\r\n    var widget = document.createElement(\"div\");\r\n\r\n    widget.className = \"ab-custom-wa-button\";\r\n    widget.setAttribute(\"dir\", \"rtl\");\r\n\r\n    widget.innerHTML = `\r\n      <a href=\"${link}\"\r\n         class=\"whats-cta ab-custom-wa-link\"\r\n         target=\"_blank\"\r\n         rel=\"nofollow noopener\"\r\n         data-chat-channel=\"${chatChannel}\"\r\n         data-chat-placement=\"button\"\r\n         data-chat-link=\"${link}\">\r\n        <span>تحدث مع طبيب</span>\r\n      </a>\r\n    `;\r\n\r\n    document.body.appendChild(widget);\r\n\r\n    document.addEventListener(\r\n      \"click\",\r\n      function (e) {\r\n        var linkEl = e.target.closest(\".ab-custom-wa-link\");\r\n\r\n        if (!linkEl) return;\r\n\r\n        var props = {\r\n          chat_channel: linkEl.dataset.chatChannel,\r\n          chat_placement: linkEl.dataset.chatPlacement,\r\n          chat_link: linkEl.dataset.chatLink || linkEl.href,\r\n          device_type: IS_MOBILE ? \"mobile\" : \"desktop\",\r\n          page_path: location.pathname,\r\n          page_type: pageType,\r\n          utm_source: utm_source,\r\n          utm_campaign: utm_campaign,\r\n          gclid: gclid\r\n        };\r\n\r\n        pushEvent(Object.assign({ event: EVENT_NAME }, props));\r\n        pushCleverTap(CLEVERTAP_EVENT_NAME, props);\r\n      },\r\n      true\r\n    );\r\n  });\r\n})();\r\n","subscribe_ribbon_title":"","subscribe_ribbon_body":"","subscribe_ribbon_link":"","mobile":{"sticky_repo_link":"https://go.altibbi.com/global","inread_link":"https://go.altibbi.com/global","inread_answer_link":"https://go.altibbi.com/global","inread_qa_link":"https://go.altibbi.com/global","inread_article_ribbon_link":"https://go.altibbi.com/global","inread_term_ribbon_link":"https://go.altibbi.com/global","navbar_cta":"https://go.altibbi.com/global","lab_test_cta":"https://go.altibbi.com/global","preg_header_cta":"https://go.altibbi.com/global","riaya_link":"https://go.altibbi.com/global","homepage_cta":"https://go.altibbi.com/global","quiz_cta_link":"https://go.altibbi.com/global","drug_inread_link":"https://go.altibbi.com/global","q_and_a_banner":"https://go.altibbi.com/global","header_call_cta":"https://go.altibbi.com/global","header_chat_cta":"https://go.altibbi.com/global","mental_health_wa_link":"https://go.altibbi.com/global","nav_cta_link":"https://go.altibbi.com/global"},"desktop":{"sticky_repo_link":"https://go.altibbi.com/global","inread_link":"https://go.altibbi.com/global","inread_answer_link":"https://go.altibbi.com/global","inread_qa_link":"https://go.altibbi.com/global","inread_article_ribbon_link":"https://go.altibbi.com/global","inread_term_ribbon_link":"https://go.altibbi.com/global","navbar_cta":"https://go.altibbi.com/global","lab_test_cta":"https://go.altibbi.com/global","preg_header_cta":"https://go.altibbi.com/global","riaya_link":"https://go.altibbi.com/global","homepage_cta":"https://go.altibbi.com/global","quiz_cta_link":"https://go.altibbi.com/global","drug_inread_link":"https://go.altibbi.com/global","q_and_a_banner":"https://go.altibbi.com/global","header_call_cta":"https://go.altibbi.com/global","header_chat_cta":"https://go.altibbi.com/global","mental_health_wa_link":"https://go.altibbi.com/global","nav_cta_link":"https://go.altibbi.com/global"}};
    let ENABLE_NAVIGATOR_STICKY = 1;
    let ENABLE_CONTENT_NAVIGATOR = 1;
    let IS_CLARITY_ENABLE = 1;
  </script>
  <!-- AdBlockers Detector  -->
  <div id="ad-blocker-detector">
   <div class="adBanner">
   </div>
  </div>
  <!-- Google Tag Manager (noscript) -->
  <noscript>
   <iframe height="0" src="https://www.googletagmanager.com/ns.html?id=GTM-WHXVK4VT" style="display:none;visibility:hidden" width="0">
   </iframe>
  </noscript>
  <!-- End Google Tag Manager (noscript) -->
  <!--header-->
  <header class="sticky-top bg-white" id="header">
   <nav class="new-navbar navbar navbar-expand-xl navbar-light bg-white position-relative py-2 py-xl-3 border-bottom border-gray-6">
    <div class="container d-flex align-items-center justify-content-between">
     <div class="d-flex align-items-center">

In [13]:
books=soup.find_all(class_='question-item-container')

In [14]:
books[0]

<div class="question-item-container">
<div class="d-flex justify-content-between align-items-center flex-wrap">
<div class="age">
<span class="font-regular">سؤال من </span>
            ذكر 28 سنة        </div>
<a class="category-info d-block" href="/%D8%A7%D9%85%D8%B1%D8%A7%D8%B6-%D8%A7%D9%84%D8%AC%D9%87%D8%A7%D8%B2-%D8%A7%D9%84%D8%AA%D9%86%D9%81%D8%B3%D9%8A">أمراض الجهاز التنفسي</a>
</div>
<div itemprop="mainEntity" itemscope="" itemtype="https://schema.org/Question">
<a class="question-text mt-17 id-5-5" href="https://altibbi.com/اسئلة-طبية/%D8%A7%D9%85%D8%B1%D8%A7%D8%B6-%D8%A7%D9%84%D8%AC%D9%87%D8%A7%D8%B2-%D8%A7%D9%84%D8%AA%D9%86%D9%81%D8%B3%D9%8A/%D9%81%D9%8A-%D9%83%D8%AA%D9%85%D9%87-%D9%86%D9%81%D8%B3-%D8%A8%D8%AA%D8%AC%D9%8A-%D9%85%D8%B1%D8%A7%D8%AA-%D8%AD%D9%85%D9%89-%D8%A7%D8%AD%D9%8A%D8%A7%D9%86%D8%A7-1848053">
<h2 class="question-text mt-17 id-5-5" itemprop="name">
                في كتمه نفس بتجي مرات حمى احيانا هل يمكن تفسير أشعة الصدر المرفقة
            </h2>
</a>
<!-- SEO -->
<div class="hide" itemprop="acceptedAnswer" itemscope="" itemtype="https://schema.org/Answer">
<div itemprop="text">
                بحاحة تحليل للقشع مبدئيا وتابع متخصص صدرية او جهاز تنفسي للكشف سريريا الصورة تبدي ارتشاح التهابي على صرة الرئة في اليمين اكثر بحاجة بحث عن السبب .            </div>
</div>
</div>
<div class="question-tags-container-listing">
</div>
<div class="div-line"></div>
<div class="doctor-answer-fqaa justify-content-start align-items-lg-end d-flex align-items-sm-center">
<div class="d-flex justify-content-start align-items-start">
<div class="doctor-image-fqaa ml-auto">
<a href="https://altibbi.com/الدليل-الطبي/%D8%A7%D8%AD%D9%85%D8%AF-%D8%A7%D9%84%D8%A7%D8%B3%D8%B9%D8%AF-115431">
<img alt="أحمد الأسعد" height="45" loading="lazy" src="https://cdn.altibbi.com/cdn/cache/thumbs/image/2026/07/23/495c05967e9b8b2a97ca4e13ebfddb02.jpg.webp" width="45"/>
</a>
</div>
<div class="doctor-details-fqaa mr-3">
<p class="answer-fqaa mb-lg-1">أجاب عن السؤال</p>
<a class="d-block dr-name-fqaa" href="https://altibbi.com/الدليل-الطبي/%D8%A7%D8%AD%D9%85%D8%AF-%D8%A7%D9%84%D8%A7%D8%B3%D8%B9%D8%AF-115431">
                    د. احمد الاسعد                </a>
<time class="date-added-fqaa display-mobile">
<img alt="date-icon" height="9" loading="lazy" src="/theme/altibbi/images/widgets/clock.svg" width="9"/>
                    16 يوليو 2026                </time>
</div>
</div>
<time class="date-added-fqaa hide-mobile">
<img alt="date-icon" height="14" loading="lazy" src="/theme/altibbi/images/widgets/clock.svg" width="14"/>
            16 يوليو 2026        </time>
<a class="d-block see-answer-button-fqaa mr-auto" href="https://altibbi.com/اسئلة-طبية/%D8%A7%D9%85%D8%B1%D8%A7%D8%B6-%D8%A7%D9%84%D8%AC%D9%87%D8%A7%D8%B2-%D8%A7%D9%84%D8%AA%D9%86%D9%81%D8%B3%D9%8A/%D9%81%D9%8A-%D9%83%D8%AA%D9%85%D9%87-%D9%86%D9%81%D8%B3-%D8%A8%D8%AA%D8%AC%D9%8A-%D9%85%D8%B1%D8%A7%D8%AA-%D8%AD%D9%85%D9%89-%D8%A7%D8%AD%D9%8A%D8%A7%D9%86%D8%A7-1848053">
            اجابة الطبيب            <img alt="arrow" class="mr-1 display-mobile-inline" height="13" loading="lazy" src="/theme/altibbi/icons/tbi-arrow-left-thin.svg" width="7">
</img></a>
</div>
</div>

In [15]:
category=[]
question=[]
answer=[]
for book in books:
  category.append(book.a.text)
  question.append(book.find(class_='question-text mt-17 id-5-5').text)
  answer.append(book.find(class_='hide').text)

In [16]:
len(question)

7

In [17]:
books[0].find(class_='question-text mt-17 id-5-5').text

'\n\n                في كتمه نفس بتجي مرات حمى احيانا هل يمكن تفسير أشعة الصدر المرفقة\r\n            \n'

In [18]:
books[0].find(class_='hide').text

'\n\n                بحاحة تحليل للقشع مبدئيا وتابع متخصص صدرية او جهاز تنفسي للكشف سريريا الصورة تبدي ارتشاح التهابي على صرة الرئة في اليمين اكثر بحاجة بحث عن السبب .            \n'

In [19]:
import requests
from bs4 import BeautifulSoup

url = "https://altibbi.com/اسئلة-طبية/امراض-الجهاز-التنفسي?page=2"

headers = {
    "User-Agent": "Mozilla/5.0"
}

response = requests.get(url, headers=headers)
soup = BeautifulSoup(response.text, "html.parser")

questions = soup.find_all("div", attrs={"itemtype": "https://schema.org/Question"})

for q in questions:
    title = q.find("h2")
    if title:
        print(title.get_text(strip=True))

منذ شهر تقريبا مرضت بزكام قوي و كان في حرارة و الم في العضلات و استمرت الأعراض بالتدريج بالاختفاء حتى مضى اسبوعين تقريبا و بعدها اختفت كل الأعراض الا السعال...
عندما اصاب بالزكام اشعر بتعب شديد في الصدر ولا يمكنني ان التقط انفاسي بسهولو و عند اي حركة او مجهود او حتى اثناء التحدث فقط ابدأ الهث كأنني كنت امارس...
من ٤ أشهر عندي سعال قوي وبحس باختناق كثير وصار عندي ضيق تنفس وبحس بغثيان دايما بسبب السعال عملت صورته اشعه طلع عندي التهاب قصبات وأخذت ادويه ما استفدت عملت...
بس اتنفس ويدخل الأكسجين على حلقي عم حس  بوجع غريب كانه سيخ حار عم يمشي بحلقي مع كل شهيق وزفير عم اتوجع  وكمان صرلي أكثر من شهر مناخيري مسدود وفي...
اعاني من ضيق حاد في التنفس منذ 7 سنوات و كذلك توجد كرة في البطن فوق منطقة السرة بقليل و الم و خلعة و عملت تحاليل ايكوغرافي راديو كولو السكانار...
السلام عليكم ، منذ فترة تم تشخيص احد افراد عائلتي يتليف في الرئةبنسبة 30%وضع المريض جيد ولكن يعاني من نزلات برد متكررة وسعلة دائمة. شعر بقلق كبير ومستمر  وخوف بسبب...
عندي احتقان بالجيوب الأنفية وسلان قوي وحكة في الأنف والجلد يصير استخدام هذا العلاج وإني أخذ علاج ثايروكسين للغدة الدرقية

In [22]:
import requests
from bs4 import BeautifulSoup

headers = {
    "User-Agent": "Mozilla/5.0"
}

for page in range(1, 6):
    url = f"https://altibbi.com/اسئلة-طبية/امراض-الجهاز-التنفسي?page={page}"

    response = requests.get(url, headers=headers)
    soup = BeautifulSoup(response.text, "html.parser")

    questions = soup.find_all("div", itemtype="https://schema.org/Question")

    print(f"\n========== Page {page} ==========\n")

    for i, q in enumerate(questions, 1):

        question = q.find("h2")
        question_text = question.get_text(strip=True) if question else "No Question"

        answer = q.find("div", itemprop="acceptedAnswer")
        if answer:
            answer_text = answer.get_text(" ", strip=True)
        else:
            answer_text = "No Answer"

        print(f"Question {i}:")
        print(question_text)
        print("\nAnswer:")
        print(answer_text)
        print("-" * 80)

========== Page 1 ==========

Question 1:
في كتمه نفس بتجي مرات حمى احيانا هل يمكن تفسير أشعة الصدر المرفقة

Answer:
بحاحة تحليل للقشع مبدئيا وتابع متخصص صدرية او جهاز تنفسي للكشف سريريا الصورة تبدي ارتشاح التهابي على صرة الرئة في اليمين اكثر بحاجة بحث عن السبب .
--------------------------------------------------------------------------------
Question 2:
البارحه دخنت اركيله في كوفي وعند الخروج شعرت بدوخه واغمى علي ؟ ما السبب حاليا زين الحمدلله...وهل ممكن أن ترجع الدوخه مرة أخرى؟(راح اترك الاركيله

Answer:
لربما عرض من اعراض التسمم بأول اكسيد الكربون حاول الابتعاد عن التدخين.
--------------------------------------------------------------------------------
Question 3:
ضيق التنفس ، التهاب في الرئتين ، ألم في الصدر ، سعال مع بلغم ما هو مرض النفاخ الرئوي

Answer:
النفاخ الرئوي هو أحد أمراض الانسداد الرئوي المزمن (COPD)، يحدث نتيجة تلف الحويصلات الهوائية مما يسبب ضيقًا في التنفس وسعالًا مزمنًا، ويكون التدخين السبب الأكثر شيوعًا. وبحسب تقرير الأشعة المرفق، توجد تغيرات نفاخية رئوية خفيفة (Mild centrilobular emphysema) دون وجود كتل أو تجمع سوائل حول الرئة. أنصح بمراجعة اختصاصي أمراض صدرية لإجراء فحص وظائف الرئة ووضع خطة العلاج، مع الإقلاع التام عن التدخين إذا كانت المريضة مدخنة، ومراجعة الطوارئ عند حدوث ضيق شديد في التنفس أو ألم صدري شديد أو ازرقاق الشفاه.
--------------------------------------------------------------------------------
Question 4:
لا استطيع اخذ نفس عميق بمعنى تأتي ايام جيدة وممتازة وتأتي ايام لا استطيع اخذ النفس الا بالتثاؤب واذا لم استطع لا يؤثر علي... مع العلم اموري ممتازة جدا بالرياضة...

Answer:
ضروري فحص الهيموجلوبين ومخزون الحديد يسبب عدم الشعور بدخول الاكسجين للرئه يجب ان يراك طبيب اذا كانت النتائج طبيعيه
--------------------------------------------------------------------------------
Question 5:
اعاني من ضيق التنفس وتثاوب بكثرة احس وان نفسي لاتكتمل اشعر بالاختناق دوما مع العلم انا اكسجيني مليح وراديو الصدر طبيعي

Answer:
بعض الناس يكون عندهم حساسية صدر و تكون الشكوى ضيق بالتنفس فقط و بالفحص سليم و جميع العلامات الحيويه طبيعيه ولكن أيضاً هناك بعض الاسباب لضيق التنفس و تكون بسبب غير الصدر مثل فقر الدم و انخفاض الضغط و نقص بعض الفيتامينات و المعادن مثل فيتامين D, B12 و خمول في الغده الدرقيه نحتاج فحوصات مخبريه و فحص اكلينيكى للحكم الصحيح على الحاله و من ثم كتابة العلاج المناسب
--------------------------------------------------------------------------------
Question 6:
“لقد لاحظت خيوط دم صغيرة في المخاط والبلغم منذ يومين. لا أعاني من كحة أو جرح في الأنف. لدي أيضًا صداع شديد ودوخة. أحتاج نصيحة

Answer:
غالباً هذه الشكوى نتيجة حساسية أنف أو التهاب الجيوب الانفيه لأنها مصحوبه بدوخه و صداع علاجها حسب إذا كانت حساسية أنف تحتاج بخاخ انف مثل الرينوكورت مرتين يومياً لمدة 14 يوم و مضادات حساسية مثل الكلاريناز إذا كانت التهاب الجيوب الانفيه نزود مضاد حيوى مثل الاوجمتين 625 مجم اقراص ٣ مرات يومياً لمدة ٧ أيام مع العلاج السابق و بنادول للصداع عند اللزوم
--------------------------------------------------------------------------------
Question 7:
أعاني من تجمع للمخاط كثيف في البلعوم حتى الإختناف وعند خروجه أحيانا يكون مصحوب بدم مع حرقة المعدة وبرودة شديدة فالجسم  وألم  في الجهة اليمنى أسفل البطن مع إسهال شديد...

Answer:
بلغم كثيف مع اسهال مع نقص في الوزن له اسباب كثيره مثل التمدد الشعبى و الدرن الرئوي و التكيس التليفى في الرئه و ده بيكون منذ الولاده أو التهاب رئوى سواء بكتيري أو فطري نحتاج اشعه مقطعيه للصدر و تاريخ مرضى للعائله لمثل هذه الشكوى
--------------------------------------------------------------------------------

========== Page 2 ==========

Question 1:
منذ شهر تقريبا مرضت بزكام قوي و كان في حرارة و الم في العضلات و استمرت الأعراض بالتدريج بالاختفاء حتى مضى اسبوعين تقريبا و بعدها اختفت كل الأعراض الا السعال...

Answer:
بعد الاصابه بنزلات البرد المصحوبه بحراره و زكام و ألم بالجسم و الحلق نتيجة العدوى الفيروسيه بعض الناس يصابون بما يسمى تحسس مفرط للشعب الهوائيه بسبب العدوى أو ما يطلق عليه حساسية صدر و مع السعال ممكن يكون في أزيز في الصدر و كتمه أو صعوبة تنفس خصوصا بالليل أو مع المجهود. علاجه بخاخ موسع للشعب الهوائيه و كورتيزون و مضادات للحساسيه مثل المونتيلوكاست و شراب للسعال دمتم بصحه و عافيه دائمًا
--------------------------------------------------------------------------------
Question 2:
عندما اصاب بالزكام اشعر بتعب شديد في الصدر ولا يمكنني ان التقط انفاسي بسهولو و عند اي حركة او مجهود او حتى اثناء التحدث فقط ابدأ الهث كأنني كنت امارس...

Answer:
يجب مراجعة طبيب الصدرية لعمل الفحص السريري و فحص جهد الرئة و صورة طبقية للرئتين للتأكد من عدم وجود اسباب اخرى لضيق التنفس تتحفز عند الاصابة بالزكام مثل الازمة الصدرية و غيرها من الاسباب
--------------------------------------------------------------------------------
Question 3:
من ٤ أشهر عندي سعال قوي وبحس باختناق كثير وصار عندي ضيق تنفس وبحس بغثيان دايما بسبب السعال عملت صورته اشعه طلع عندي التهاب قصبات وأخذت ادويه ما استفدت عملت...

Answer:
صورة شعاعية للجيوب الانفية
الانتباه لاحماض المعدة
--------------------------------------------------------------------------------
Question 4:
بس اتنفس ويدخل الأكسجين على حلقي عم حس  بوجع غريب كانه سيخ حار عم يمشي بحلقي مع كل شهيق وزفير عم اتوجع  وكمان صرلي أكثر من شهر مناخيري مسدود وفي...

Answer:
يوجد لديك التهاب  بالمجارى التنفسيه  يرجى زيارة اقرب  مشفى لعمل الفحص  والعلاج
--------------------------------------------------------------------------------
Question 5:
اعاني من ضيق حاد في التنفس منذ 7 سنوات و كذلك توجد كرة في البطن فوق منطقة السرة بقليل و الم و خلعة و عملت تحاليل ايكوغرافي راديو كولو السكانار...

Answer:
مراجعة طبيب جهاز هضمي
--------------------------------------------------------------------------------
Question 6:
السلام عليكم ، منذ فترة تم تشخيص احد افراد عائلتي يتليف في الرئةبنسبة 30%وضع المريض جيد ولكن يعاني من نزلات برد متكررة وسعلة دائمة. شعر بقلق كبير ومستمر  وخوف بسبب...

Answer:
تحياتي لكم ،
التليف الرئوي مختلف حسب السبب و العمر و سرعة تطوره لذلك يجب اجراء دراسة كاملة للمريض و تحديد حالته ، لا ننسى ان التليف الذي سببه كوفيد- ١٩ له مكان في التشخيص
لذلك عليكم اجراء معاينة سريرية و صورة مقطعية و اجراء تخطيط تنفس مع DLCO
--------------------------------------------------------------------------------
Question 7:
عندي احتقان بالجيوب الأنفية وسلان قوي وحكة في الأنف والجلد يصير استخدام هذا العلاج وإني أخذ علاج ثايروكسين للغدة الدرقية

Answer:
سلامتك، أتمنى لك الشفاء العاجل. من المهم الانتباه للتفاعلات الدوائية خاصة مع وجود أدوية أخرى تتناولينها، وبالنسبة لاستخدام دواء onceair plus (مونتيلوكاست وليفوسيتريزين) مع علاج الغدة الدرقية (ثيروكسين): لا يوجد تداخلات دوائية معروفة بين هذين الدوائين ، ومع ذلك من الأفضل التحدث مع طبيبك الذي وصف لك دواء الغدة الدرقية، للتحقق من أن دواء الجيوب الأنفية مناسب لحالتك. يحتوي دواء onceair plus على مونتيلوكاست وليفوسيتريزين، وهو مفيد الحكة وسيلان الأنف وحساسية الجيوب الأنفية، ولكن يجب تناوله بحسب إرشادات وتوصيات الطبيب المختص. إليك بعض النصائح التي قد تفيد في التخفيف من سيلان الأنف واحتقان الجيوب الأنفية: اغسل الأنف بمحلول ملحي، مما يساعد على تنظيف الأنف وتخفيف الاحتقان. جرب استنشاق البخار، فقد يساعد في تلطيف الممرات الأنفية وتخفيف الاحتقان. اشرب الماء والسوائل الدافئة مثل الشاي أو الحساء، مما يساعد في ترطيب الجسم وتخفيف الأعراض. حاول تجنب المواد التي تهيج الأنف مثل الغبار والدخان والعطور القوية. وأود لفت انتباهك إلى ضرورة استشارة الطبيب أو الصيدلاني قبل استخدام أي علاج جديد، خاصة مع وجود أدوية أخرى تتناولها، بما في ذلك أدوية الغدة الدرقية. للمزيد: الفرق بين الزكام والحساسية: دليلك الشامل علاج التهاب الجيوب الأنفية وحلول نهائية له
--------------------------------------------------------------------------------

========== Page 3 ==========

Question 1:
لدي كحه ورشح وعطس مستمر ولا اشم رائحة ولكن اتذوق الأكل ولا اقدر ابتلع ما الحل؟

Answer:
أتمنى لك الشفاء العاجل، الأعراض التي ذكرتها تشير إلى عدة احتمالات، سأوضحها لك فيما يأتي : قد تكون هذه الأعراض دليلًا على وجود التهاب في الجهاز التنفسي العلوي. قد يكون نزلة برد أو التهاب في الجيوب الأنفية. فقدان الشم مع وجود حاسة التذوق قد يكون بسبب احتقان الأنف وليس مشكلة عصبية. صعوبة البلع قد تكون بسبب التهاب الحلق الناتج عن الكحة المستمرة. إليك بعض النصائح التي قد تساعدك في تخفيف الأعراض: الراحة: خذ قسطًا كافيًا من الراحة لمساعدة جسمك على التعافي. ترطيب الجسم: اشرب الكثير من السوائل الدافئة مثل الماء، الشاي مع العسل والليمون، أو شوربة الدجاج. استنشاق البخار: استنشاق البخار يساعد في تخفيف احتقان الأنف وتسهيل التنفس. الغرغرة بالماء والملح: قم بالغرغرة بالماء الدافئ والملح لتخفيف التهاب الحلق. أدوية بدون وصفة: يمكنك استخدام أدوية لتخفيف الأعراض مثل مسكنات الألم، مزيلات الاحتقان ، وأدوية السعال. كما أنصحك بزيارة الطبيب إذا استمرت الأعراض لأكثر من أسبوع، أو ترافقت مع ظهور أعراضٍ جديدة مثل الحمى الشديدة، أو صعوبة التنفس، أو ألم في الصدر، وذلك لإجراء الفحوصات اللازمة وتييم حالتك بشكلٍ أدق. للمزيد: ما أعراض التهاب الحلق البكتيري وعلاجه؟ ما مدة التهاب الحلق؟ ومتى يجب استشارة الطبيب؟
--------------------------------------------------------------------------------
Question 2:
قبل ثلاث أيام صار عندي سيلان بالأنف وتعب شديد بالجسم ثاني يوم نفس الشي بس كحة خفيفة الآن صدري يوجعني وكحة شديدة وسيلان بالأنف وجع شديد بالجسم استخدمت الأدوية المرفقة...

Answer:
أتمنى لك الشفاء العاجل، من الواضح أنك تعاني من أعراض تشبه أعراض البرد أو الإنفلونزا، وقد يكون تطور الحالة إلى ألم في الصدر والسعال الشديد يشير إلى التهاب في الجهاز التنفسي، وقد تشير الأعراض التي تعاني منها إلى: التهاب الشعب الهوائية: وهو التهاب في الشعب التي تحمل الهواء إلى الرئتين، ويسبب السعال وألم الصدر. التهاب رئوي: وهو عدوى في الرئتين قد تسببها البكتيريا أو الفيروسات، وتتسبب في السعال والحمى وألم الصدر. الإنفلونزا: يمكن أن تسبب الإنفلونزا أعراضًا مشابهة، ولكن قد تتطور إلى مضاعفات مثل التهاب الشعب الهوائية أو الالتهاب الرئوي. وبما أنك لم تتحسن بعد استخدام هذه الأدوية، وفي حال استمرار الأعراض لأكثر من 7 أيام، أو في حال ارتفعت حرارة جسمك، أنصحك بمراجعة طبيب مختص بأمراض الجهاز التنفسي لتقييم حالتك ووصف العلاج الأنسب لك. ويمكن للنصائح الآتية أن تساعدك في تخفيف سيلان الأنف والأعراض الأخرى: الراحة: تأكد من الحصول على قسط كافٍ من الراحة، مما يساعد الجسم على التعافي. شرب السوائل: تناول الكثير من الماء والسوائل الدافئة مثل الشاي مع العسل والليمون لتخفيف الاحتقان وتهدئة الحلق. استخدام مرطب الهواء: يمكن أن يساعد استخدام مرطب الهواء في ترطيب الممرات الهوائية وتخفيف السعال. تجنب المهيجات: تجنب التدخين والتعرض للملوثات الأخرى التي قد تزيد من تهيج الجهاز التنفسي. مسكنات الألم: تناول المسكنات التي لا تستلزم وصفة، مثل الباراسيتامول أو الإيبوبروفين بعد استشارة الصيدلي أو الطبيب. المحلول الملحي: قد يساعد استخدام بخاخ الأنف المكون من محلول ملحي من تخفيف سيلان واحتقان الأنف. للمزيد: الفرق بين الزكام والحساسية: دليلك الشامل ما هو احسن دواء للبرد والأنفلونزا حسب الأعراض؟
--------------------------------------------------------------------------------
Question 3:
السلام عليكم دكتور عندي ضيق في التنفس وگحه قويه فيها صوت مزعج وبلغم ايضاً قوي هاي الايام وانا حامل في الشهر السابع وتعبت كثيراً من الگحه ماذا افعل تجيني الگحه...

Answer:
أتمنى لكِ السلامة، هذه الأعراض قد تكون مزعجة بالفعل، خاصة في الثلث الأخير من الحمل، وقد يكون هناك عدد من الأسباب المحتملة للسعال وضيق التنفس مع البلغم أثناء الحمل ، بما في ذلك التهابات الجهاز التنفسي، أو الربو أو ارتجاع المريء، أو حتى الحمل ذاته قد يسبب ضيقاً في التنفس بسبب ضغط الرحم على الحجاب الحاجز. سأقدم لكِ أهم النصائح التي قد تفيدك في التخفيف من الأعراض في المنزل: الراحة: احصلي على قسط كافٍ من الراحة لمساعدة جسمك على التعافي. شرب السوائل: اشربي الكثير من الماء والسوائل الدافئة مثل الشاي بالليمون والعسل لتخفيف البلغم وتهدئة الحلق. ترطيب الهواء: استخدمي جهاز ترطيب الهواء في غرفة النوم، خاصة في الليل، لتخفيف السعال . الغرغرة بالماء والملح: يمكن أن تساعد الغرغرة بالماء والملح الدافئ في تهدئة الحلق وتخفيف الاحتقان. تجنب المهيجات: تجنبي التدخين والروائح القوية والملوثات الأخرى التي قد تزيد السعال. رفع الرأس: عند النوم، ارفعي رأسك بوسادة إضافية لتسهيل التنفس وتخفيف السعال الليلي. العسل: ملعقة صغيرة من العسل قبل النوم يمكن أن تساعد في تهدئة السعال. وفي حال استمرار السعال والبلغم، أو في حال تفاقم الأعراض أنصحكِ بمراجعة طبيب مختص بأمراض الجهاز التنفسي لتقييم حالتك وتشخيصها ، ووصف العلاج المناسب، دون أن يسبب أي أضرار لكِ أو لطفلك. للمزيد: علاج الكحة للحامل، وهل للكحة أثر على الجنين؟ ما هو أفضل علاج للكحة عند الكبار والصغار؟
--------------------------------------------------------------------------------
Question 4:
اعاني من ضيق بالتنفس بشكل صعب حيث لا استطيح سحب النفس بشكل كامل يحدث عندما احاول الاستلقاء ويستمر في بعض الاحيان لفترات طويلة فيصبح عندي الم بالجهة اليسرى من القفص...

Answer:
أتمنى لكِ الصحة والعافية، قد تشير أعراض ضيق التنفس والألم في الجهة اليسرى من القفص الصدري التي تعانين منها إلى عدة احتمالات، منها: مشاكل في الجهاز الهضمي: مثل الارتجاع المريئي، حيث يمكن أن يسبب ضيقًا في التنفس وألمًا في الصدر. مشاكل في الرئة: مثل الربو أو التهاب الشعب الهوائية، وقد تزداد الأعراض عند الاستلقاء. القلق والتوتر: قد يسبب كل منهما ضيقًا في التنفس وشعورًا غير مريح في الصدر. مشاكل في القلب: قد يكون هناك علاقة بين ضيق التنفس والألم في الصدر ومشاكل القلب، خاصةً عند الاستلقاء. أسباب أخرى: مثل مشاكل في العضلات والأعصاب في منطقة الصدر. أنصحكِ بمراجعة طبيب مختص بأمراض الصدر والبطن لتقييم حالتك بشكل دقيق، وقد يحتاج الأمر لإجراء بعض الفحوصات والصور للتحقق وتحديد التشخيص الصحيح، وبالتالي وصف العلاج المناسب. ويمكن للنصائح الآتية أن تفيدك في تخفيف ألم الصدر و ضيق التنفس ريثما تزورين الطبيب: حاولي الجلوس بشكل مستقيم أو رفع رأسك وكتفيك بوسائد إضافية عند الاستلقاء. تجنبي الأطعمة الثقيلة أو الدهنية قبل النوم. مارسي تمارين التنفس العميق والاسترخاء لتقليل التوتر والقلق. إذا كنتِ تعانين من الربو أو أي مشاكل تنفسية أخرى، تأكدي من استخدام الأدوية الموصوفة بانتظام. خذي قسطًا من الراحة وتجنبي الأنشطة البدنية الكثيفة. للمزيد: أسباب ضيق التنفس عند المشي، وطرق الوقاية ما أسباب وعلاج ضيق التنفس عند النوم
--------------------------------------------------------------------------------
Question 5:
اشعر بوجود شي عالق في منطقة البلعوم ولا اعرف ما هو بلغم او شي اخر ويسبب لي ضيق في التنفس مع وجود انتفاخ في المعدة

Answer:
ربما تعاني من ارتدتد مفرزات الجيوب الانفية الى منطقة البلعوم و شعور بوجود جسم غريب  يجب المراجعة الطبية و التاكد من احماض المعدة
--------------------------------------------------------------------------------
Question 6:
صعوبة التنفس والم الرئة اليمني واليسرى والم القلب أحيانا وسعال مزمن وحاد والشعور بالدم في فمي والفشل والم تحت الرئة اليمني والقفص الصدري احيانا والتعرق والغثيان و الم الكلى

Answer:
نصيحة لابد من العرض على الطبيب وفحص سريري واشعة ، ربما هذه علامات التهاب رئوي شديد لانه يمتد الالم إلى البطن وتشعر بألم اثناء التنفس
--------------------------------------------------------------------------------
Question 7:
طعنة في الشق الأيسر أعلى الصدر أحيانا تكون مصحوبة بضيق في التنفس، وعادة ما تأتي بعد بذل مجهود

Answer:
أتمنى لك السلامة والعافية، وإنّ الأعراض التي ذكرتها قد يمكن السيطرة عليها بسهولة إذا تمت متابعتها، فهي تطلب اهتمامًا فوريًا لمعرفة سببها، فقد ترتبط بعدة حالات صحية، مثل: القلق والتوتر الشديدين. شد عضلي، أو التهاب عضلي صدري. مشاكل في الرئة، مثل التهاب غشاء الرئة. مشاكل في القلب، مثل الذبحة الصدرية. فإذا كان الألم يستمر لفترة طويلة أو يزداد مع النشاط البدني، فمن الأفضل مراجعة الطبيب ليفحصك سريريًا، وقد يجري لك بعض الفحوصات اللازمة، مثل تخطيط القلب أو الأشعة، للتأكد من سبب هذه الأعراض لاتخاذ الإجراء المناسب، ووضع الخطة العلاجية الأنسب، كما أنصحك بطلب العناية الطبية الطارئة إذا لاحظت صاحب هذه الأعراض دوخة وغثيان، أو ألم يمتد للراع، أو ألم مستمر لا يزول حتى مع الراحة. وبشكلٍ عام أنصحك بتطبيق الإرشادات التالية فقد تساعد في التخفيف من هذه الأعراض : الزم الراحة وتجنب المجهود الزائد. تجنب التدخين والملوثات الهوائية. حافظ على نظام غذائي صحي ومتوازن. مارس تمارين الاسترخاء لتقليل التوتر والقلق. للمزيد: 5 احتمالات وراء اسباب الم الصدر والفرق بينها اسباب ضيق التنفس المرتبطة بمشكلات القلب والرئتين
--------------------------------------------------------------------------------

========== Page 4 ==========

Question 1:
بحس دايما كأن فى حاجة ضغطة على صدرى باحس انى ببذل مجهود علشان اعرف آخذ نفسى كويس و بحس انى لازم آخذ نفس عميق علشان احس براحة و ساعات بتجيلى...

Answer:
أتمنى لكِ العافية، شعورك بضيق في الصدر وصعوبة في التنفس مع نغزات هو أمر يجب الانتباه إليه، وقد يكون له عدة أسباب محتملة، بما في ذلك: القلق والتوتر: يمكن أن يسبب كل من الضيق والتوتر ضيقًا في التنفس وشعورًا بالضغط على الصدر. مشاكل في الجهاز التنفسي: مثل الربو أو التهاب الشعب الهوائية، حيث يمكن أن تسبب صعوبة في التنفس ونغزات. مشاكل في الجهاز الهضمي: مثل ارتجاع المريء، يمكن أن يسبب ألمًا في الصدر. مشاكل في العضلات والعظام: قد يكون هناك التهاب في عضلات الصدر أو مشاكل في الأضلاع تسبب الألم عند التنفس. أسباب أخرى: قد تكون النغزات وألم الصدر علامة على مشاكل قلبية، خاصة إذا كانت مصحوبة بضيق في التنفس. أنصحكِ بمراجعة طبيب مختص بأمراض الصدر للفحص وتقييم الحالة، وقد يحتاج الأمر إجراء بعض الفحوصات والصور للتحقق من التشخيص الصحيح، وبالتالي وصف العلاج المناسب، ومن المستحسن الحصول على مشورة أخصائي صحة نفسية أيضًا. وقد تساعدكِ النصائح والتدابير المنزلية الآتية في تخفيف الأعراض: تقنيات التنفس العميق: حاولي أن تتنفسي ببطء وعمق من خلال الأنف، واحبسي النفس لبضع ثوانٍ ثم أخرجيه ببطء من الفم. الاسترخاء: مارسي تقنيات الاسترخاء مثل التأمل واليوغا لتقليل التوتر والقلق. تجنب المهيجات: تجنبي المواد التي تزيد من تفاقم الأعراض مثل ملوثات الهواء والتدخين والروائح القوية. الراحة: احصلي على قسط كافٍ من النوم والراحة. للمزيد: اسباب ضيق التنفس المرتبطة بمشكلات القلب والرئتين أسباب ضيق التنفس عند التوتر، وأهم طرق علاجه
--------------------------------------------------------------------------------
Question 2:
عمري 20 سنة مدخن من 5 سنين بمتوسط 5 الى 12 سيجارة اقلعت من 50 يوم بعد ما اقلعت عم اشعر بضيق تنفس دائم ومؤخراً نخزة طفيفة بالجهة اليسار من...

Answer:
سلامتك، أتفهم قلقك بشأن ضيق التنفس والأعراض الأخرى التي تشعر بها بعد الإقلاع عن التدخين، سأبين لك الأسباب المحتملة لهذه الأعراض على النحو الآتي: أعراض انسحاب النيكوتين: يمكن أن تشمل ضيق التنفس والقلق، خاصة في الفترة الأولى بعد الإقلاع عن التدخين. تأثير التدخين على الرئة: حتى بعد الإقلاع، قد يستغرق الجهاز التنفسي بعض الوقت للتعافي. التدخين يمكن أن يسبب التهابًا وتضيقًا في القصبات الهوائية. أسباب أخرى: قد تكون هناك أسباب أخرى غير مرتبطة بالتدخين مثل القلق، مشاكل في القلب، أو مشاكل في الجهاز التنفسي. وقد تساعدك النصائح الآتية في التخفيف من ضيق التنفس والأعراض الأخرى المزعجة: تمارين التنفس: جرب تمارين التنفس العميق والاسترخاء لتهدئة الجهاز التنفسي وتقليل الشعور بضيق التنفس. الترطيب: اشرب كميات كافية من الماء للحفاظ على رطوبة الجسم وتسهيل عملية التنفس. تجنب المهيجات: ابتعد عن الأماكن التي تحتوي على دخان أو ملوثات قد تزيد من تهيج الجهاز التنفسي. ممارسة الرياضة بانتظام: قم بممارسة التمارين الرياضية الخفيفة بانتظام لتحسين صحة القلب والرئة، ولكن تجنب الإفراط في المجهود. الراحة والاسترخاء: حاول الحصول على قسط كافٍ من النوم والراحة، وتجنب الإجهاد والقلق. وأنصحك بمراجعة طبيب مختص بأمراض الجهاز التنفسي للفحص والاطمئنان واستبعاد وجود مشكلة خطيرة، خاصةً إذا كان ضيق التنفس شديدًا ويمنعك من ممارسة الأنشطة اليومية، أو إذا كان هناك ألم حاد في الصدر، وقد تحتاج لإجراء بعض الصور والفحوصات للتحقق من السبب الدقيق. للمزيد: اسباب ضيق التنفس او الزلة التنفسية وطرق علاجها طرق فعالة لتنظيف الرئتين بعد الإقلاع عن التدخين
--------------------------------------------------------------------------------
Question 3:
اعاني من حساسية صدرية وسعال شديد مصحوب ببلغم بالليل والنهار وتعب اثناء المشي ذهبت لدكتور الصدرية اخبرني انه كان لدي كورونا وهذه نتائج عنها ولدي التهاب بالقصبات الهوائية  تناولت دواء...

Answer:

In [32]:
import requests
from bs4 import BeautifulSoup
import time
import pandas as pd

headers = {
    "User-Agent": "Mozilla/5.0"
}

classes = [
    "امراض-الغدد-الصماء",
    "مرض-السكري",
    "امراض-الجهاز-التنفسي",
    "امراض-الدم",
    "امراض-الاطفال"
]

data = []

for category in classes:

    print("\n" + "=" * 100)
    print(f"Category: {category}")
    print("=" * 100)

    for page in range(1, 200):

        url = f"https://altibbi.com/اسئلة-طبية/{category}?page={page}"

        while True:

            response = requests.get(url, headers=headers)

            if response.status_code == 429:
                print("429 Too Many Requests")
                print("Waiting 30 seconds...\n")
                time.sleep(30)
                continue

            if response.status_code != 200:
                print(f"Error: {response.status_code}")
                break

            break

        soup = BeautifulSoup(response.text, "html.parser")

        questions = soup.find_all(
            "div",
            itemtype="https://schema.org/Question"
        )

        if not questions:
            print(f"No questions found in Page {page}")
            continue

        print(f"\n========== Page {page} ==========\n")

        for i, q in enumerate(questions, 1):

            question = q.find("h2")
            question_text = question.get_text(strip=True) if question else "No Question"

            answer = q.find("div", itemprop="acceptedAnswer")
            answer_text = answer.get_text(" ", strip=True) if answer else "No Answer"


            data.append({
                "Category": category,
                "Page": page,
                "Question_ID": i,
                "Question": question_text,
                "Answer": answer_text
            })


            print(f"Question {i}:")
            print(question_text)
            print("\nAnswer:")
            print(answer_text)
            print("-" * 80)

        time.sleep(2)


df = pd.DataFrame(data)

df.drop_duplicates(
    subset=["Question"],
    inplace=True
)

df.reset_index(drop=True, inplace=True)


print(df.head())

print("Dataset Shape:", df.shape)


df.to_csv(
    "medical_dataset.csv",
    index=False,
    encoding="utf-8-sig"
)

print(f"Total Questions Collected = {len(df)}")

Streaming output truncated to the last 5000 lines.

Answer:
لا يوجد شيء اسمه روماتزم مرتفع!
ماهو الفحص؟
وان كانت استأصلت اللوزتين فلماذا تضرب إبر؟
هل هي إبر مضاد حيوي؟
سلامتها
--------------------------------------------------------------------------------
Question 3:
أعطيت طفلي ١٥ نقطه فيدروب يوميا قريب شهر كلمت دكتور الاطفال تبعه قال لي اوقف الفيدروب تماما واراقب الطفله ولكن انا خايفه عليها اريد اضمن هل عليها ضرر أو شو...

Answer:
حسب تركيز  الدواء.وقد يحتاج بعض الفحوصات.سلامته
--------------------------------------------------------------------------------
Question 4:
رضيعي ٤ اشهر يرضع طبيعي ولديه حساسيه مثل الطفح الجلدي في وجهه وجسمه شخصت اكزيما سببها حليب الام. وشف له منذ ٥ ايام حليب اليمنتال،لكن الحساسيه مستمرة مع هيجان مصاحب...

Answer:
لا يجوز إيقاف حليب الأم نهائيا حتى لو كان السبب للاكزيما مع أنني أشك.
سلامتها
--------------------------------------------------------------------------------
Question 5:
طفل 7شهر  اصيب بسحايا بعمر يوم ادت الى كهرباء زائده في الدماغ يحدث نوبات اختلاج لأقل من دقيقتين تحدث  النوبات يومياً تقريباً 10 مرات الطفل الأن لا يبتسم لا يبكي...

Answer:
مراجعة طبيب أعصاب أطفال فوراً.سلامته
--------------------------------------------------------------------------------
Question 6:
ابنتى عمرها ٤ شهور البراز لون مائل ل الاخضر و له حبيبات سوداء و مخاط دم ورائحته كريهه ولديها حساسيه البان

Answer:
فحص براز.ثم مراجعة طبيب الأطفال.سلتمتها
--------------------------------------------------------------------------------
Question 7:
مرحبا بنتي شهرين ونص رفضت الرضاعة الطبيعبة نهائي و ترضع صناعي كانت اول شهر ونصف ترضع كتير منيح و تجوع وتبكي و تاخد الرضعة بلهفة من عمر شهر ونص لحد...

Answer:
مشكلة كبيرة تعويد الطفل على الحليب الصناعي بجانب الطبيعي.من المفترض أن ترضع طبيعي فقط!
حاولي شفطي حليبك وحطيلها اياه بالرضاعة.سلامتها
--------------------------------------------------------------------------------

========== Page 102 ==========

Question 1:
بنتي عمرها سنه ونص حراره ٣٨ وترجيع لونه اصفر وديتها مستشفى واخذت ادول في الوريد بس لسى بعد ٣ ساعات والحراره ٣٧.٧ ايش اعطيها والترجيع مستمر

Answer:
اذا كان الإقياء مستمراً فلابد من دخول المستشفى
--------------------------------------------------------------------------------
Question 2:
ماهو علاج جرثومه المعده لانثى بعمر 13 سنه ووزن65 كيلو ..مع العلم ان نتيجه تحليل h.pylori ag in stool  هو 24.8

Answer:
هل الطفل بيشتكي كثيرا ولالاالعلاج علاج دوائيله اكثر من نظام ومدهنرجع لطبيب الاطفال او جهاز هصمي للعلاج
--------------------------------------------------------------------------------
Question 3:
طفلي عمره 8 شهور يوسخ حول 6 مرات في اليوم ويستحدم حليب نارولاك هل بسببه

Answer:
قد يكون تبرز الطفل بهذا الشكل طبيعيا مع بعض الرضع شريطة أن يصاحب ذلك نموا طبيعيا بمعدلات الوزن والطول وتطورات طبيعيا في النمو الحركي والعصبي .
خلاف ذلك لابد من مراجعة الطبيب الخاص لتحديد سبب الإسهال وعلاجه
--------------------------------------------------------------------------------
Question 4:
طفلتي عمره سنتين قبل اربع ايام ارتفعت حرارته و اليوم الثالث  راحت الحراره منه
اليوم رابع يوم رجعت الحراره وعطيته تحميله بالفجر وبليل ارتفعت ل 38.8 عطيته تحميله وبعد ست...

Answer:
اذا كانت تحاميل paracetamol فلا مانع من استخدامها كل ٦ ساعات.
أما تحاميل diclofenac sodium فلا ينصح باستخدامها نهائيا كخافض حرارة في الأطفال.
السبب يتحدد بعد الفحص.
سلامتها
--------------------------------------------------------------------------------
Question 5:
لو سمحت اديت قطرة باراسيتامول بالخطأ فى انف الرضيع عمر ٣ أسابيع بدل من اوتريفين بيبى سالاين ، هل هذا خطر وماذا افعل؟

Answer:
كلا لا يوجد خطر.سلامتها
--------------------------------------------------------------------------------
Question 6:
مغص ويرقان وبلغم وصوت شاحب اثناء الانين

Answer:
هذا فحص cbc فقط وهو طبيعي لا علاقة له باليرقان ولا بالصوت الشاحب.
--------------------------------------------------------------------------------
Question 7:
السلام عليكم ورحمة الله وبركاته
وضعت مولودتي بفضل الله وكرمه على خير متى أبدأ بإعطاء الفيدروب لها؟ وسقطت سرتها بعد اتمام خمس أيام من الولادة ويوجد بعض قطرات من الدماء...

Answer:
السلام عليكم....نبدأ vidrop من اول يوم ولاده ...الجرعه اربع نقط بالفم مره يوميا مستمر
--------------------------------------------------------------------------------

========== Page 103 ==========

Question 1:
كم قطره اعطي ابني عمره ١٩ يوم... وزنه ٣ كيلو

Answer:
ما هو سبب أخذ الدواء أصلا؟معظم الأطفال لا يحتاجون فيتامينات متعددة بهذا العمر
--------------------------------------------------------------------------------
Question 2:
ابنتي عمرها ٩ اشهر قبل ٣ اشهر ثقبنا لها أذنها وامس لاحظت تورم في اذنها ازلت الحلق من اذنها و ينزل من اذنها مثل القيح سوايل مع دم
اشتريت لها...

Answer:
السلام عليكم...ارجو عدم استعمال اي حلق في هذه الاذن الابعد ان تتحسن تماما و بعد ذلك ارجو استخدام حلق طبي حتي لا يتكرر هذا الالتهاب
--------------------------------------------------------------------------------
Question 3:
شهيته احيانا ياكل جيدا  واحيانا يقفل عن الاكل وهو شقي مايجلس على الاكل ابدا ااكله وهو يدور وزنه ٩ كيلو وطوله ٧٢ ورحت عند دكتور اعطاني ديكال ب١٢ وفيتامين حديد...

Answer:
يرجي عمل تحاليل انيميا وفتامينات للطفل لتحديد العلاج المناسب له
--------------------------------------------------------------------------------
Question 4:
تزوج اخي من احد الأقارب وانجب بنتان توائم وتمت الولادة قيصرية بعد إكمال 15 يوم في التاسع وبعد الولاده كان كل شيء طبيعي لمدة يومين ولكن ظهر بعض الأعراض كعدم...

Answer:
حسب التشخيص.حسب ماهو المرض الوراثي
--------------------------------------------------------------------------------
Question 5:
لدي طفل رضيع عمره 7 اشهر و يمر بمرحلة التسنين و ارتفعت درجة حرارته  فاصبحت ب37.5هل هذا بسبب التسنين ؟

Answer:
الفحص هو اللي يحدد السبب
--------------------------------------------------------------------------------
Question 6:
بقعه عند طفله ٩ سنوات في اسفل البطن من الناحيه الشمال مش بتوجع و مش بتروح بقالها سنه هل هي خطره

Answer:
مستحيل معرفة الخطورة او التشخيص دون فحصها
--------------------------------------------------------------------------------
Question 7:
أبني مولود بقالوا ٧ أيام وعنده دمامل في رقبته وتحت باطه كتير حلها ايه

Answer:
مرطب لهذه الاماكن وتهويتها ومسح العرق باستمرار
--------------------------------------------------------------------------------

========== Page 104 ==========

Question 1:
السادة الافاضل
تحية طيبة وبعد،
ارجو من سيادتكم بافادتنا بمدى خطوره هذا الورم الدموى المرفق بالصور وعلاجه والفترة الزمنية التى يتم ظهوره فيها ومتى يتم الشفاء منه .
مع العلم...

Answer:
نستشير دكتور جراحه تجميل او اطفال في حقن بيكون مناسب بعض الوحمات الدمويه بعد الفحص بيحدد وبتتحسن وبتقل خالص
--------------------------------------------------------------------------------
Question 2:
بنتي من عمرها شهر الى الان عمرها 4 أشهر وهي ماتم عمليه لاخراج بصوره صحيحه اله اني اسويلها تحفيز يله تم تبقئ 3الئ 4 ايام وهي ماتخرج. ورضاعه طبيعيه شنو...

Answer:
لا يجوز التحفيز طبعا.لا بد من مراجعة طبيب الأطفال لفحصها.سلامتها
--------------------------------------------------------------------------------
Question 3:
السلام عليكم
بنتي عمرها ١٢ سنه لديها ضعف في التركيز وصعوبات تعلم مرفق صورة التحاليل الطبية برجاء الافادة هل هذة النسب عامل اساسي لمشكلة الدراسة والتركيز وكم جرعات ادوية مناسبة

Answer:
الأنيميا العاليه توثر جدالازم فحص جيد وعلاج مظبوطالاهتمام بالتغذيه من مكسرات ومنتجات بحر لزياده الاوميجا ٣نقلل ساعات الموبايل والتلفزيونالنوم بدري
--------------------------------------------------------------------------------
Question 4:
بنتي عمرها اربع سنوات اخذت حبه اوميغا مابلعتها عضتها حتى الزيت نزل في فمها ورمتها هل ياثر عليها

Answer:
لا يؤثر.سلامتها
--------------------------------------------------------------------------------
Question 5:
السلام عليكم بنتي عمرها شهرين ونصف طلبلها طبيبها مرنان مغناطيسي للدماغ .. بالمركز طلبو تصوم من ال12 ليلا يعني حوالي عشر ساعات هل هذا شيء منطقي علما انه صعب جدا...

Answer:
طبيب التخدير هو الأقدر على تقييم وضعها قبل الإجراء.سلامتها
--------------------------------------------------------------------------------
Question 6:
سلام الله عليكم طفلتي عمرها ٥سنوات تعاني من شحنات في الدماغ وبتحصل لها تشنجات والان بنستخدم لها علاج كبراديل واتضح لي بأنه مايعالجش الحاله وإنما كمهدئ للتشنجات فقط .. أفيدونا...

Answer:
طبيب أعصاب الأطفال فقط هو الأقدر على المساعدة بعد.عمل التخطيط الدماغي والفحوصات اللازمة.سلامتها
--------------------------------------------------------------------------------
Question 7:
طفلي ٣ شهر لاحظت من يومين انه يمسك اذنه اليسار كانه يحك ولاحظت انه يغمض عينه اليسار كانه يغمز ...لاحظت الحركه مايقارب ٥ مرات من يومين فهل لها علاقه ببعض...

Answer:
يفضل زيارة الطبيب.سلامته
--------------------------------------------------------------------------------

========== Page 105 ==========

Question 1:
استفساري هو ان بنتي لها ٣ ايام تعاني من حراره واستفراغ والحراره تهدأ مع التحاميل (ادول١٢٥) والمشروب ايبروفين طبعا كل يوم في المستشفى ناخذ مضاد ومغذي فهل طبيعي انها تطول...

Answer:
نعم طبيعي.لكن حسب وضعها وفحصها ونتائج فحوصاتها.سلامتها
--------------------------------------------------------------------------------
Question 2:
ابني عمره 50 بتشردق وبنخنق من ريقه وهو بيرضع كمان ذهبت الى طبيب قال الي عنده ارخاء بالحنجره وشكرا لكم

Answer:
ده ارتجاع في المري وليس ارتخاءتنظيم الرضاعه وياخذ علاج للارتجاع
--------------------------------------------------------------------------------
Question 3:
عند استعمال مرهم بيبروتاكت يبكي الصغير ماهو السبب

Answer:
مكوناته مع بعض الاطفال بتعمل حرقان في الجلد
--------------------------------------------------------------------------------
Question 4:
بنتى عندها 3سنوات عيونها صفرا ومفيش اعراض الترجيع ولا السخونية ولا تغير لون البول والبراز عملت تحليل للصفرا طلعت النسبة 5.28 فيه شك فى انيميا الفول او متلازمة جلبرت المفروض...

Answer:
لا بد من المتابعة مع الطبيب الذي طلب الفحوصات فهو الأقدر على تقييم الحالة.سلامتها
--------------------------------------------------------------------------------
Question 5:
عملت لطفلي تحليل وابغى قراءه النتايج اذا كان فيروسي او بكتيري

Answer:
الفحص هو الي يحدد في حالته اكتر من التحاليل
--------------------------------------------------------------------------------
Question 6:
لو طفل عمره سنة تناول دواء دلتا فيت B12 (يحتوي القرص على 1000 ميكروجرام من سيانوكوبالامين)، ماذا يجب أن نفعل في هذه الحالة؟ وهل لهذا الدواء أعراض جانبية خطيرة؟ وهل...

Answer:
أتمنى لطفلك السلامة، ما أنصحك به في هذه الحالة: الاتصال بمركز السموم: أول وأهم خطوة هي الاتصال بمركز السموم في بلدك على الفور. هم الأقدر على تقييم الوضع بناءً على كمية الدواء التي تناولها الطفل ووزنه وحالته الصحية. لا تحاولي التقيؤ: لا تحاولي جعل الطفل يتقيأ إلا إذا نصحك بذلك مركز السموم أو الطبيب. المراقبة الدقيقة: راقبي طفلك عن كثب بحثًا عن أي أعراض غير طبيعية مثل: الغثيان أو القيء الإسهال الطفح الجلدي أو الحكة صعوبة التنفس تورم في الوجه أو اللسان الدوار أو فقدان الوعي هل لدواء دلتا فيت B12 أعراض جانبية خطيرة؟ عادةً، فيتامين B12 آمن نسبيًا حتى بجرعات عالية، ونادرًا ما يسبب أعراضًا جانبية خطيرة. ومع ذلك، نظرًا لأن الطفل صغير جدًا، وتناول جرعة كبيرة نسبيًا، فمن المهم توخي الحذر. هل من الضروري الذهاب إلى المستشفى؟ يعتمد ذلك على نصيحة مركز السموم، وعلى حالة الطفل. إذا ظهرت على الطفل أي أعراض مقلقة، أو إذا أوصى مركز السموم بذلك، فمن الضروري الذهاب إلى أقرب مستشفى على الفور.
--------------------------------------------------------------------------------
Question 7:
اعطيت بالغلط ابني عمره 6 سنوات علاج مضاد اوس ونس كل 6 ساعات والدكتور كاتبلي مره كل اربعه وعشرون ساعه هل يضره

Answer:
نعم ممكن أن يحدث ضرر.يفضل زيارة الطوارئ.سلامته
--------------------------------------------------------------------------------

========== Page 106 ==========

Question 1:
طفلي لا يعاني من حساسية اللاكتوز ولكن لعدم توفر البديل اعطيتة خالي لاكتوز كيف يمكن تعويض النقص طفلي عمرة سبع اشهر
ويعاني من الاسهال ايضا

Answer:
حليب خالي اللاكتوز فتره الاسهال فقط ونعالج سبب الإسهال وعندما يقف الاسهال نرجع للحليب العادي بالتدريج
--------------------------------------------------------------------------------
Question 2:
طفلي يبلغ من العمر خمس سنوات ابتلع خاتم فضي حجمه يمكن ٣سم  وسوينا له اشعه وطلع الخاتم في المعده وصار له يوم كامل و١٢ساعه  وانا اراقب الإخراج عنده الله يكرمكم...

Answer:
يمكنك متابعة براز الطفل لمدة ثلاثة أيام...وتعاد الاشعه حال عدم خروجه...
--------------------------------------------------------------------------------
Question 3:
ابني شهر ونصف بيرضع طبيعي فقط بيقعد فتره ٤ ايام مش بيعمل ستول بديله لبوسه جليسرين ف بيعمل حمام حصل الموضوع دا كدا مرتين دا امر طبيعي ولا عاوز زياره...

Answer:
يفضل طبعا زيارة الطبيب لتقييم نظامه الغذائي وفحصه.سلامته
--------------------------------------------------------------------------------
Question 4:
ماهو سبب ظهور هذه البقعة لبنتي عمرها 3 سنوات ونصف علماً انها لاتسبب اي حكة او ازعاج لها هل هذه تكون مثيرة لقلق ام لا وماهو الهلاج الى مثل هكذا...

Answer:
عزيزتي السيدة/السيدة (اسم المريضة)،
نشكرك على التواصل وثقتك في استشارتنا الطبية. بناءً على الوصف الذي قدمته، من الصعب تشخيص الحالة بدقة بدون فحص شخصي. ولكننا سنقدم لك بعض المعلومات العامة.
البقع التي تشرحين عنها قد تكون ناتجة عن عدة أسباب محتملة مثل الإصابة بالحساسية، الطفح الجلدي أو التغيرات البقعية الطبيعية في البشرة. ومن المهم مراقبة البقعة وملاحظة أي تغيرات في حجمها أو شكلها أو لونها بمرور الوقت.
إذا كنتم قلقين بشأن البقعة، ننصحكم بزيارة طبيب الأطفال لتقييم الحالة بشكل دقيق. قد يطلب الطبيب إجراء فحوصات إضافية أو استشارة أخصائي آخر إذا أرى ذلك ضروريًا.
بالنسبة للاحتمال الأخير "الهلاج"، فهو حالة جلدية تتميز بظهور بقع ذات لون أبيض-فاتح على الجلد، ولكن يُفضل مشاهدتها وتقييمها من قبل طبيب مختص لتحديد التشخيص الدقيق وتوجيه العلاج المناسب.
ننصحكم بالاطمئنان وعدم التوتر، وإجراء زيارة طبية قريبة لتقييم حالة ابنتكم بشكل كامل. نحن هنا لمساعدتكم والإجابة على أسئلتكم.
--------------------------------------------------------------------------------
Question 5:
تشخيص صورة دم لطفل عمرة سنة ، Mild microcytic hypochromic anemia with anisocytosis.
Absolute neutropenia.
Relative lymphocytosis.
Iron profile, Hb electrophoresis & Follow up are recommended
مرفق صورة من تحليل...

Answer:
هل تم عمل تحليل انيميا الفول ومخزون الحديد ولالالان ده ممكن انيميا نقص حديدوفحص الطفل بيحدد اكتر مش التحاليل بس
--------------------------------------------------------------------------------
Question 6:
طفل 9 اشهر ظهر له هذا الطفح الجلدي  للعلم الطفح بدون ارتفاع عن سطح الجلد و في مناطق معينه من الجسم للمرة الثانية ويختفي شكينا انه حساسية غذائية قطعنا الموز...

Answer:
سلامته.لا بد من فحصه لمعرفة التشخيص
--------------------------------------------------------------------------------
Question 7:
مرحبا بنتي عمرها شهرين وزنها ٥ كيلو ولا ترضع طبيعي ترضع صناعي فقط ٦٠ ميلي كل ٣ ساعات ما بتاخد اكتر من ٦٠ هيك مناسب ؟؟

Answer:
لا بد من فحصها أولا وتقييم نموها.سلامتها
--------------------------------------------------------------------------------

========== Page 107 ==========

Question 1:
ابنتي عشر شهور لحظت منذ اكثر من اسبوع ان فخدها الشمال من الخلف من بدايته  حتي ركبتها لونه اصفر و هي بشرتها بيضاء و ملمس هذة المنطقة مختلف قليلا عن...

Answer:
لا يمكن العلاج قبل الفحص.سلامتها
--------------------------------------------------------------------------------
Question 2:
ابني عمره 10 سنين بدأت ألحظ عليه قبل اسبوع او 10 ايام اصفرار في الجسم وبالأخص العينين والاحظ تغير لون البرل الى الداكن مع الاصفرار الشديد ومغص في البطن وتعب...

Answer:
لا بد من فحصه طبعاً.سلامته
--------------------------------------------------------------------------------
Question 3:
لدي طفلة حديثة الولادة قام مستوصف العائلة في الحي بفحص اخذ قطرات دم على ورقة من كعب القدم لكن اعطوني النتيجة ولم اعرف ماهي المشكلة جزاك الله خير ان تخبرني...

Answer:
اللغة غير مفهومة.
والأرقام المذكورة غير واضح ما هو الحد الطبيعي لها.تابعي مع المركز الصحي نفسه.سلامتها
--------------------------------------------------------------------------------
Question 4:
طفله عمرها سنتين وفي عدد ٢ خراج في الجبهه وتم امبارح فتح الخراج عند اخصائى جراحه ووضع فتيل في كل خراج ولكن بدون بنج بناءا على كلام الدكتور والطفله صرخت...

Answer:
لا تحتاج لتخدير فالعمليه بسيطه والألم بها خفيف يمكن تحمله
--------------------------------------------------------------------------------
Question 5:
ابني عمره اسبوع ويعاني من مغص جربت salinal drops وما استفاد عليه
بدي دواء للمغص

Answer:
قد يكون ذلك بالفعل بسبب لين في غضاريف الحنجرة والقصبه الهوائية وهو مرض يتحسن تدريجيا بمرور الوقت.او يكون بسبب ضيق أو اعوجاج بالانف..
--------------------------------------------------------------------------------
Question 6:
ابنتي عمرها ٧ سنوات تعاني من رجفه غير متواصله بعد فحص فيتامين دال كان عندها ١٤ هل سبب الرجفه  وكم ملي اعطيها من الفيتامين لتعويض النقص

Answer:
لا بد من فحصها أولاً لمعرفة سبب الرجفة.
جرعة فيتامين دال تتحدد حسب وضعها الصحي وحسب تركيز الدواء نفسه.سلامتها
--------------------------------------------------------------------------------
Question 7:
بنتي عندها شهر ونص من يوم ما اتولدت بتحرك رجليها واديها كتير جدا ممكن تتقلب وهي نايمة كل الناس بتقولي حركتها كتير علي سنها ده ممكن يكون دليل علي حاجة...

Answer:
لا يوجد تشخيص لمرض فرط الحركة في عمر الشهرين.
ولا يوجد طفل عمره شهرين قادر على أن يقلب من ظهره إلى بطنه أو بالعكس.
سلامتها
--------------------------------------------------------------------------------

========== Page 108 ==========

Question 1:
ابني عنده سنه و٣ شهور قطع الرضاعه الطبيعيه وانا زرت طبيب الأطفال وقال لي لا تأخذين ادويه لتنشيف اللبن الا بعد شهر وانا صدري وجعني جدا وهو قطع الرضاعه تماما...

Answer:
تستطيعين شفط الحليب وإعطاؤه للطفل بالكأس.
وإن رفض فلا مانع..سنة وثلاثة أشهر فترة جيدة وكافية
--------------------------------------------------------------------------------
Question 2:
السلام عليكم
طفلي عمره يومين اكرمكم الله برازه يخرج مثل حبات السمسم متماسك وليس سائل هل يدعي هذا مراجعة طبيب وما سبب ذلك

Answer:
لا توجد مشكله وسوف يتغير براز طفلك مع استمرارك بالرضاعة وتحسن جودة الرضاعه الطبيعيه
--------------------------------------------------------------------------------
Question 3:
ابني عمره 3 سنوات فجأة اصبح يفتح فمه ولا يستطيع بلع لعابه ويتكلم بصعوبة و لعابه غزير جدا المرجو المساعدة

Answer:
قد يكون ذلك بسبب التهاب أو تضخم باللوزتين او وجود تقرحات بالحلق او اللسان أو اللثه...مراجعة الطبيب ضروريه للفحص
--------------------------------------------------------------------------------
Question 4:
ولدي عمره الان اسبوع ودايم فاتح فمه من اول يوم ولاده ، هل هذا طبيعي ؟
ولون شفايفه غامقه ، مع العلم ولدي بشرته سمرا
هل طبيعي غمقان الشفايف
وشكراً

Answer:
يفضل فحصه.سلامته
--------------------------------------------------------------------------------
Question 5:
طفلتي عندها ثلاثه اشهر ودائما ترجع حليب خفيف بعد الرضاعه رحت للطبيب الاول وحكا هذا شي طبيعي والطبيب الثاني كمان نفس القصه شي طبيعي مع شوية ادويه للمعده شو تنصحوني...

Answer:
ننصح بالمتابعة مع اختصاصي الأطفال الذي قام بفحصها.أسباب الترجيع كثيرة..بعضها طبيعي وبعضها مرضي.سلامتها
--------------------------------------------------------------------------------
Question 6:
قدمها توجد فيها حراره دائما عند وضعها في الماء البارد عندها ترتاح ماذا افعل في هذه الحاله علما الحاله عندها تقريبا ٩ اشهر

Answer:
لا توجد حرارة دون ارتفاع في درجة حرارة الجسم
--------------------------------------------------------------------------------
Question 7:
طفلي بعمر ثمانيه اشهر سقط من سرير وبكه بكاء قليل وسكت هل يحتاج فحص. وذهار لطبيب ورجع طبيعي

Answer:
نعم بحاجة لفحص.سلامته
--------------------------------------------------------------------------------

========== Page 109 ==========

Question 1:
السلام عليكم طفلي عمره ١١ شهر ووزنه ١٠ كيلو وشوي كم اعطيه مل الدكتور الي رحت له قال ١ مل بعدين غير كلامه وقال ٣ مل والوصفه الطبيه مكتوب ٥...

Answer:
الجرعة تختلف حسب تركيز الدواء.
مضاد الأموكسيكلاف يأتي بتراكيز مختلفة
--------------------------------------------------------------------------------
Question 2:
لدي طفلين توام ولدو بالاسبوع ٣٤ عندهم اضراب عن الرضاعه ياتي فترات ولكن تتزايد شدته مع تقدمهما بالعمر يرضعون صناعي عمرهم ٤ اشهر تم تغيير نوع الحليب اكثر من مره...

Answer:
الافضل نعمل اختبار تحسس حليب البقر واذا ايجابي يتم تغيير الحليب الي Nan supreme ونشوف الاستجابه
--------------------------------------------------------------------------------
Question 3:
ولدي عمره 8 سنوات عليه حراره من البارح اعطيه فيفادول كل 4 ساعه تنزل شوي وترجع قبل اسبوع كان عنده احتقان بالحلق خفيف ووصف اي الدكتور مضاد لو جته حراره...

Answer:
الرجاء اعطاء جرعة مناسبة من خافض الحرارة كل 6 ساعات زلمدة 48 ساعة مع مراقبة حثيثة لدرجة الحرارة و نشاط الطفال ومراقبة ظهور اي اعراض اخرى - في حال اسمرت الحرارة يجب معاينة الطفل وتقييمه من قبل طبيب
--------------------------------------------------------------------------------
Question 4:

In [42]:
df.head()

,Category,Page,Question_ID,Question,Answer
0,امراض-الغدد-الصماء,1,1,لا يوجد اي اعراض سوي أنها متضخمه\r\nده تحليل ا...,بحاجة صورة ومضانية للغدة الدرقية Cintilografi...
1,امراض-الغدد-الصماء,1,2,حامل في الاسبوع التاسع نشاط في الغدة يوجد نقص ...,ارتفاع هرمونات الغدة تعمل هيك اعراض مثل الخفقا...
2,امراض-الغدد-الصماء,1,3,تعب وخمول وزيادة في الوزن والم في اسفل الظهر و...,الفحوصات تظهر نقص في مستوى الكالسيوم و فيتامين...
3,امراض-الغدد-الصماء,1,4,تحليل tsh. 32.7\r\nومع ذلك لا توجد اعرض واضحة ...,ينصح بمراجعة طبيب صماء .\nالنتيجة مرتفعة و عدم...
4,امراض-الغدد-الصماء,1,5,الام شديدة بالبطن تشبه التشنجات وارهاق وتعب شد...,السلام عليكم، صحيح تعداد كريات الدم البيضاء مر...

In [43]:
df = pd.read_csv("medical_dataset.csv")

In [44]:
import pandas as pd
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM

model_name = "Qwen/Qwen2.5-1.5B-Instruct"

tokenizer = AutoTokenizer.from_pretrained(model_name)

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    torch_dtype="auto",
    device_map="auto"
)

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

In [45]:
def generate_qwen_answer(question):

    messages = [
        {
            "role": "system",
            "content": (
                "أنت مساعد للإجابة عن الأسئلة الطبية. "
                "أجب عن السؤال باللغة العربية بناءً على المعلومات الطبية المتاحة. "
                "قدم إجابة واضحة ومباشرة."
            )
        },
        {
            "role": "user",
            "content": question
        }
    ]

    text = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True
    )

    inputs = tokenizer(
        text,
        return_tensors="pt"
    ).to(model.device)

    with torch.no_grad():

        outputs = model.generate(
            **inputs,
            max_new_tokens=200,
            do_sample=False
        )

    generated_tokens = outputs[0][
        inputs["input_ids"].shape[1]:
    ]

    answer = tokenizer.decode(
        generated_tokens,
        skip_special_tokens=True
    )

    return answer.strip()

In [46]:
from sentence_transformers import SentenceTransformer

similarity_model = SentenceTransformer(
    "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
)

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

In [47]:
def calculate_similarity(
    ground_truth,
    model_answer
):

    embeddings = similarity_model.encode(
        [ground_truth, model_answer],
        convert_to_tensor=True
    )

    score = torch.nn.functional.cosine_similarity(
        embeddings[0].unsqueeze(0),
        embeddings[1].unsqueeze(0)
    ).item()

    return score

In [48]:
question = df.iloc[0]["Question"]

qwen_answer = generate_qwen_answer(question)

ground_truth = df.iloc[0]["Answer"]

similarity_score = calculate_similarity(
    ground_truth,
    qwen_answer
)

print("Question:")
print(question)

print("\nQwen Answer:")
print(qwen_answer)

print("\nGround Truth:")
print(ground_truth)

print("\nSimilarity Score:")
print(f"{similarity_score:.4f}")

print("\nSimilarity Percentage:")
print(f"{similarity_score * 100:.2f}%")

Question:
لا يوجد اي اعراض سوي أنها متضخمه
ده تحليل اخويا عنده 38 سنه ومعندهوش اي امراض مزمنه

Qwen Answer:
عذرًا، ولكنني لا أستطيع تقديم المشورة الطبية أو التقييم الطبي عبر هذه الميزة. إذا كان لديك أي أسئلة طبية، يرجى التواصل مع طبيب أو مستشار صحي محترف.

Ground Truth:
بحاجة صورة ومضانية للغدة الدرقية  Cintilografia of thyroid gland لمعرفة العقدة هل هية حارة ام باردة التحاليل لاتبدي على اضداد لقصور درق مناعي ذاتي كمرض هاشيموتو اذا كانت العقدة باردة على الصورة .غالبا بحاجة خزعة بالإبرةاما اذا كانت حارة حمراء . ممنوع لمسها وعادية كإلتهاب نسيجي عموما الصورة ستعطينا نتيجة .

Similarity Score:
0.2078

Similarity Percentage:
20.78%

In [51]:
results = []

for index, row in df.head(10).iterrows():

    question = row["Question"]
    ground_truth = row["Answer"]

    # Generate Qwen answer
    qwen_answer = generate_qwen_answer(question)

    # Calculate similarity
    similarity_score = calculate_similarity(
        ground_truth,
        qwen_answer
    )

    results.append({
        "Question": question,
        "Ground_Truth": ground_truth,
        "Qwen_Answer": qwen_answer,
        "Similarity_Score": similarity_score,
        "Similarity_Percentage": similarity_score * 100
    })

    print(f"Processed {index + 1}/10")

Processed 1/10
Processed 2/10
Processed 3/10
Processed 4/10
Processed 5/10
Processed 6/10
Processed 7/10
Processed 8/10
Processed 9/10
Processed 10/10

In [54]:
results_df = pd.DataFrame(results)

results_df.to_csv(
    "qwen_evaluation_results.csv",
    index=False,
    encoding="utf-8-sig"
)

print("\nAverage Similarity Score:")
print(results_df["Similarity_Score"].mean())

print("\nAverage Similarity Percentage:")
print(results_df["Similarity_Percentage"].mean())

Average Similarity Score:
0.44871039539575575

Average Similarity Percentage:
44.87103953957558

In [55]:
results_df.head()

,Question,Ground_Truth,Qwen_Answer,Similarity_Score,Similarity_Percentage
0,لا يوجد اي اعراض سوي أنها متضخمه\r\nده تحليل ا...,بحاجة صورة ومضانية للغدة الدرقية Cintilografi...,عذرًا، ولكنني لا أستطيع تقديم المشورة الطبية أ...,0.207839,20.783862
1,حامل في الاسبوع التاسع نشاط في الغدة يوجد نقص ...,ارتفاع هرمونات الغدة تعمل هيك اعراض مثل الخفقا...,هذا يبدو أنه سلوك غير طبيعي ولا يمكن أن يكون ل...,0.512891,51.289093
2,تعب وخمول وزيادة في الوزن والم في اسفل الظهر و...,الفحوصات تظهر نقص في مستوى الكالسيوم و فيتامين...,هذه بعض العلامات التي قد تشير إلى الإصابة بمرض...,0.683405,68.340534
3,تحليل tsh. 32.7\r\nومع ذلك لا توجد اعرض واضحة ...,ينصح بمراجعة طبيب صماء .\nالنتيجة مرتفعة و عدم...,تحليل TSH (ترابط هيدروكربونات السيلينيوم) هو ع...,0.400139,40.013883
4,الام شديدة بالبطن تشبه التشنجات وارهاق وتعب شد...,السلام عليكم، صحيح تعداد كريات الدم البيضاء مر...,تشخيص حالتك يتطلب زيارة طبيب متخصص، لكن يمكنني...,0.371592,37.159169